Repository KusionStack/karpor, pull requests merged in 2024-08, with the labels that each got.

#571 feat(ui): control whether the Github logo is displayed
  ui/src/components/layout/index.tsx
  ui/src/store/modules/globalSlice.ts
Labels: area/experience

#574 refactor: adjust ui to adapt github-badge flag, refine makefile
  Makefile
  ui/src/components/layout/index.tsx
Labels: area/experience, chore

#536 feat(robustness): add liveness check and readiness check
  go.mod
  go.sum
  pkg/core/health/check.go
  pkg/core/health/check_status_handler.go
  pkg/core/health/check_test.go
  pkg/core/health/storage_check.go
  pkg/core/route/route.go
  pkg/core/route/route_test.go
  pkg/infra/persistence/elasticsearch/client.go
  pkg/infra/search/storage/elasticsearch/factory.go
  pkg/infra/search/storage/elasticsearch/resource.go
  pkg/infra/search/storage/types.go
  pkg/kubernetes/registry/search/factory.go
  pkg/kubernetes/registry/search/storage_provider.go
Labels: area/server

#604 fix: wrong link for create token guide
  ui/src/pages/login/index.tsx
Labels: area/experience
