Repository KusionStack/karpor, pull requests merged in 2024-05, with the labels that each got.

#443 feat: add cert generator
  .licenserc.yaml
  hack/cert-generator/generator/generator.go
  hack/cert-generator/generator/util.go
  hack/cert-generator/go.mod
  hack/cert-generator/go.sum
  hack/cert-generator/main.go
  hack/cert-generator/option.go
  hack/gen-cli-docs/main.go
Labels: enhancement

#464 docs: refine contribute part in readme
  README.md
Labels: documentation

#465 docs: add readme-zh.md
  README-zh.md
Labels: documentation

#469 fix(ui): some experiences problmes
  ui/src/components/sqlSearch/index.tsx
  ui/src/pages/search/index.tsx
  ui/src/utils/constants.ts
Labels: area/experience

#471 feat(ui): added german translations
  ui/src/components/layout/index.tsx
  ui/src/i18n.js
  ui/src/index.tsx
  ui/src/locales/de.json
  ui/src/utils/constants.ts
Labels: area/experience

#472 docs: add a new contributor to readme, welcome!
  .all-contributorsrc
  README-zh.md
  README.md
Labels: documentation

#475 docs: add a new contributor intro of virtually-stray to readme
  .all-contributorsrc
  README-pt.md
  README-zh.md
  README.md
Labels: documentation

#473 fix: missing placeholder text in i18n files
  ui/src/components/sqlSearch/index.tsx
  ui/src/locales/de.json
  ui/src/locales/en.json
  ui/src/locales/zh.json
  ui/src/pages/result/index.tsx
Labels: area/experience

#467 chore(ci): different tags trigger different release pipelines
  .github/workflows/release.yaml
  .goreleaser/.goreleaser-dev.yml
  .goreleaser/.goreleaser.yml
Labels: chore, governance

#476 refactor(ui): easier to add new language for i18n
  ui/src/components/layout/index.tsx
  ui/src/index.tsx
  ui/src/utils/constants.ts
Labels: area/experience
